//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP.Foliacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancelaciones_InterfazPercepcionesDeduccionesCompensados_IPDC
    {
        public int Id { get; set; }
        public int IdReferenciaCancelados { get; set; }
        public string TipoNom { get; set; }
        public string Cve_presup { get; set; }
        public string CveGto { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string TipoClave { get; set; }
        public string Num_che { get; set; }
        public string CveReal { get; set; }
        public string CveCompen { get; set; }
        public string fecha { get; set; }
        public Nullable<int> IdctaBanca { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public string Num { get; set; }
        public string NomAlpha { get; set; }
        public string Quincena { get; set; }
        public string Adicional { get; set; }
        public string Cla_pto { get; set; }
        public Nullable<int> Ldf_6d { get; set; }
        public Nullable<int> AnioEnReferencia { get; set; }
    }
}
