//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP.Foliacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Permisos
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public int IdRol { get; set; }
        public int IdModulo { get; set; }
        public bool Activo { get; set; }
    
        public virtual Login_Modulos Login_Modulos { get; set; }
        public virtual Login_Roles Login_Roles { get; set; }
        public virtual Login_Usuarios Login_Usuarios { get; set; }
    }
}
